### ISSUE TITLE
Is there a way to make aggregateReference faster.

### ISSUE THREAD

**Issue by smk5g5** [LTLA/SingleR#101] opened 2020-03-24 22:25 UTC
Hi,

I am using Single cell RNA-sequencing data to create a reference. I was wondering if there is a way to make it faster. The way I am running at this moment it takes forever to run aggregate reference on single cell RNA-seq data.

```
 aggr_train <- aggregateReference(sce_HDV3_train, labels=HDV3_train@active.ident,BPPARAM = bpparam())
```

**Comment by LTLA** [comment] 2020-03-25 07:05
Yes, the GitHub version (which will eventually find its way into BioC-devel) has:

- PCA before k-means.
- Parallelization via _BiocParallel_.
- Options to enable subsetting to genes of interest, e.g., markers or HVGs.

**Comment by dtm2451** [comment] 2020-06-15 02:49
closing as it seems the issue is addressed already in the development version.

**Closed by dtm2451** 2020-06-15 02:49 UTC
