### ISSUE TITLE
Singler error when more than 900 cells

### ISSUE THREAD

**Issue by huwenhuo** [LTLA/SingleR#181] opened 2021-04-17 12:24 UTC
my code is like 

mtsx = seurat.obj@assay$RNA@data[, 1:800]
 ref.data = HumanPrimaryCellAtlasData()
 pred = SingleR(test = mtx, assay.type.test=1, ref=ref.data, labels = ref.data$label.main

When more than 800 cells:
Error in h(simpleError(msg, call)):
error in evaluating the argument 'x' in selecting a method for function 'as.list': error in evaluating the argument 'flesh' in selecting a method for function 'relist': object 'facy_mseq' not found.

When less than 800 cells, I got DataFrame with likely correct results with columns scores, first.labels, tuning.scores, labels, and pruned.labels. 

Any suggestion?

**Comment by LTLA** [comment] 2021-04-19 08:09
There is no restriction on the number of cells that can be supplied to `SingleR` - the examples in the [book](http://bioconductor.org/books/release/SingleRBook/) frequently use more than 800 cells. I don't know what `facy_mseq` is, either; no such variable exists in the SingleR code base.

Create a minimum reproducible example, then we might make some progress. The code snippet you've provided has obvious problems so it's hard to know what you did wrong. Why do you assign to `mtsx` but then use `test = mtx`? What's in the rest of the `SingleR()` function call, given that you didn't show the closing parentheses?

**Comment by j-andrews7** [comment] 2021-07-09 13:47
Closing this due to no response, feel free to comment/re-open if you're still having issues.

**Closed by j-andrews7** 2021-07-09 13:47 UTC
