### ISSUE TITLE
Want to know the unregulated and down regulated genes in particular cell type .

### ISSUE THREAD

**Issue by sdabral05** [LTLA/SingleR#127] opened 2020-05-25 12:35 UTC
hi ,

My idea is to follow Single R annotation pipeline which will give me exact labels according to reference data and after that use this data to seurat package to calculate DEGs within the cell and between two different cells . also want to plot UMAP type distribution plot.
Code i have used :::
`hpca.se <- HumanPrimaryCellAtlasData()
hpca.se

matrix.data <- Read10X(data.dir = "//scRNA/GI/filtered_feature_bc_matrix/")
singler = SummarizedExperiment(assays =list(counts=matrix.data) )

test1 <- scater::logNormCounts(singler)

pred.hesc <- SingleR(test = test1, ref = hpca.se, labels = hpca.se$label.main , de.method="wilcox")
pred.hesc
table(pred.hesc$labels)
seurat[["pred.hesc.labels"]] <- pred.hesc$labels
`

This work perfectly.

But after this I am not able to get what i want . 
code i want to use is ::
`cluster1.markers <- FindMarkers(pbmc, ident.1 = 1, min.pct = 0.25)
`
But this is taking my seurat object .

One more question ::
Can we normalized the data with seurat package than load object to singleR for annotation . Is this possible .

**Comment by friedue** [comment] 2020-05-25 12:50
If you want to export the `SingleR` results back into a `Seurat` object, follow the description in [`SingleR`'s landing page](https://github.com/LTLA/SingleR/#usage-with-seuratsinglecellexperiment-objects), essentially `seurat.obj[["SingleR.labels"]] <- singler.results$labels`. 

Alternatively, you can do the marker gene detection using BioConductor functions, too:

```
markers.pbmc <- findMarkers(sce.pbmc)
```

Details [here](https://osca.bioconductor.org/marker-detection.html).

>Can we normalized the data with seurat package than load object to singleR for annotation . Is this possible .

Yes. All you need for SingleR is the **matrix** of normalized expression values, your `test1` object does not have to be a `SingleCellExperiment` object.

**Comment by sdabral05** [comment] 2020-05-26 04:31
Thank you  for the nice explanation.

I getting this Waring message while running  SingleR(). Is this because of data matrix do not have major differentiate values or is this because of reference data .
```
pred.hesc <- SingleR(test = test1, ref = hpca.se, labels = hpca.se$label.main , de.method="wilcox")
Warning message:
In .pairwise_blocked_template(x, group.vals, nblocks = length(block),  :
  no within-block comparison between Neuroepithelial_cell and BM & Prog.
```

**Comment by LTLA** [comment] 2020-05-26 06:36
I'll field this one.

It is caused by the lack of replicates for `Neuroepithelial_cell` and `BM & Prog.` in the HPCA dataset. If you don't have replicates, there's not much point running a statistical test, hence the warning. In practice, if there are not too many of these warnings, they can be safely ignored...

However! I notice that you have set `de.method="wilcox"` in this run. This is a bad idea for the built-in references where there is little replication. The Wilcoxon rank sum test only considers the ranks of expression values, and when you only have 2-3 replicates for each group (at best), you will end up with many genes that are tied on the same p-value. This compromises selection of good markers because the test cannot distinguish between genes with weak stochastic separation in the expression distribution and those that are genuinely label-specific markers. 

If you must use a test-based procedure, you would be better served by setting `de.method="t"` instead - though one wonders why you feel the need to change this argument in the first place.

**Comment by sdabral05** [comment] 2020-05-26 08:12
Hi, @LTLA , I am new to this pipeline , I am trying it with different method .Thank you for pointing this. By running it with `de.method ="t"` ,it give more gene differentiation before previous one .

@friedue  the document you have share which give maker gene before running singleR().
I want answer of :
Gene list which expressed in Neutrophils with their fc and p value which represent how many gene have high expression and how many gene are low expressed?

Data I am using -

 ```
sce.pbmc
class: SingleCellExperiment 
dim: 33538 1125 
metadata(1): Samples
assays(2): counts logcounts
rownames(33538): MIR1302-2HG FAM138A ... AC213203.1 FAM231C
rowData names(3): ID Symbol Type
colnames(1125): AAACCTGAGAAACGCC-1 AAACCTGAGTGGGATC-1 ... TTTGTCAGTAAGGGCT-1
  TTTGTCAGTGACCAAG-1
colData names(3): Sample Barcode label
reducedDimNames(3): PCA TSNE UMAP
spikeNames(0):
altExpNames(0):
```
And than I run -
```
`sce <- SingleR(test = sce.pbmc, ref = hpca.se, labels = hpca.se$label.main , de.method="t")
markers.pbmc <- findMarkers(sce.pbmc)
Error in FUN(x, groups, ..., log.p = TRUE) : 
  argument "groups" is missing, with no default
seurat <- CreateSeuratObject(counts = matrix.data, project = "human")
> seurat[["sce.labels"]] <- sce$labels
Error: Cannot add more or fewer cell meta.data information without values being named with cell names
`
```

Document which you have attached suggest to use findMarkers().I want to subset data with the name to cell which come out after singleR().

**Comment by sdabral05** [comment] 2020-05-26 14:21
Hi ,

https://osca.bioconductor.org/hca-human-bone-marrow-10x-genomics.html#clustering-14

Chapter 37 : 

1. read raw data 
2. normalization 
3 . clustering PCA, umap, tsne
From these step I can get number clusters denoted by me only  but we don't have any idea which cluster belongs two cell type .
4. use singleR()
I am confused .
In my head -
Condition should be like If I am calculating 12 cluster than by using Single R It should tell me which cluster belongs to which cell type .I am right or not.
BY my code -
By seen results ,I am not able to find able to relate it . 
Not able to fetch gene which showing up regulation(high expression ) into particular cell .

Please guide me what I am doing wrong .

**Comment by LTLA** [comment] 2020-05-27 07:16
I have no idea what you're asking, or what your problem is, or whether it's even related to **SingleR**. Can you try explaining your situation again but more clearly?

**Comment by dtm2451** [comment] 2020-06-15 03:59
Closing due to the lack of reply, but feel free to reopen or create a separate issue if your confusion remains.

**Closed by dtm2451** 2020-06-15 03:59 UTC
