### ISSUE TITLE
Error: subscript contains invalid names

### ISSUE THREAD

**Issue by smk5g5** [LTLA/SingleR#179] opened 2021-03-15 21:16 UTC
I am trying to run multiple references with SingleR and I am getting the following error

`shared <- Reduce(intersect, list(rownames(novershtern2),rownames(neftel_sce10x2),rownames(neftel_sce2_ss2)))
combined <- cbind(novershtern2[shared,], neftel_sce10x2[shared,],neftel_sce2_ss2[shared,])`

`Error: subscript contains invalid names
In addition: Warning message:
In methods:::.selectDotsMethod(classes, .MTable, .AllMTable) :
 `
Any idea what may be going  wrong colData has only one variable in the above code `CellAssignment`

`novershtern2@colData <- novershtern2@colData[c('CellAssignment')]

novershtern2$CellAssignment <- paste0('Noversh.',novershtern2$CellAssignment)

neftel_sce10x2 <- neftel_sce10x

neftel_sce10x2@colData <- neftel_sce10x2@colData[c('CellAssignment')]

neftel_sce10x2$CellAssignment <- paste0('Neftel_10x',neftel_sce10x2$CellAssignment)`

Still I am getting this error. Any pointers will be appreciated. Thanks!

**Comment by LTLA** [comment] 2021-03-15 22:30
Is there actually a **SingleR** problem here? I don't see any reference to **SingleR** functions.

**Comment by smk5g5** [comment] 2021-03-15 22:33
These are all single cell experiment objects. I am trying to follow examples in the book https://bioconductor.org/books/3.12/SingleRBook/using-multiple-references.html but I am getting error at the `combined <- cbind(novershtern2[shared,], neftel_sce10x2[shared,],neftel_sce2_ss2[shared,])` step.

**Comment by LTLA** [comment] 2021-03-17 07:35
This is not a **SingleR** problem. Your error is not occurring at any **SingleR** functions. You should instead figure out why your `cbind` isn't working, given that's really where the problem is.

Consider making a [minimum reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example#:~:text=Basically%20a%20minimal%20reproducible%20example,run%20on%20the%20given%20dataset) so that I don't have to try to guess what the issue is. And post your session information.

**Comment by j-andrews7** [comment] 2021-07-09 13:53
Closing due to no info/response. Feel free to re-open with more info.

**Closed by j-andrews7** 2021-07-09 13:53 UTC
